<a href="https://colab.research.google.com/github/asryan11/food_rep/blob/main/food_rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow
!pip install nltk
!pip install pandas
!pip install numpy
!pip install sklearn
#!pip install tensorflow_decision_forests

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (71.0.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.64.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow) (0.1.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.5.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
import pandas as pd
import numpy as np
import nltk
import csv
from nltk import word_tokenize
from nltk.corpus import stopwords
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tensorflow import keras
from tensorflow.keras import layers
#import tensorflow_decision_forests as tfdf
import tensorflow as tf

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/ML Projects/Food Recipe LLM/Cleaned_Indian_Food_Dataset.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5938 entries, 0 to 5937
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TranslatedRecipeName    5938 non-null   object
 1   TranslatedIngredients   5938 non-null   object
 2   TotalTimeInMins         5938 non-null   int64
 3   Cuisine                 5938 non-null   object
 4   TranslatedInstructions  5938 non-null   object
 5   URL                     5938 non-null   object
 6   Cleaned-Ingredients     5938 non-null   object
 7   image-url               5938 non-null   object
 8   Ingredient-count        5938 non-null   int64
dtypes: int64(2), object(7)
memory usage: 417.6+ KB

In [ ]:
df.isnull().sum()

TranslatedRecipeName      0
TranslatedIngredients     0
TotalTimeInMins           0
Cuisine                   0
TranslatedInstructions    0
URL                       0
Cleaned-Ingredients       0
image-url                 0
Ingredient-count          0
dtype: int64

In [ ]:
train = df.drop(['TranslatedIngredients', 'TotalTimeInMins', 'Cuisine', 'URL', 'image-url'], axis=1)

In [ ]:
# lem= WordNetLemmatizer()
# for i,row in df.iterrows():
#   filter_sentence=[]
#   sentence=row['directions']
#   sentence=re.sub(r'[^\w\s]','',sentence)
#   words=nltk.word_tokenize(sentence)
#   words=[w for w in words if not w in stop_words]
#   for w in words:
#     filter_sentence.append(lem.lemmatize(w))
#   print(filter_sentence)
#   df.loc[i,'directions']=' '.join(filter_sentence)

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5938 entries, 0 to 5937
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TranslatedRecipeName    5938 non-null   object
 1   TranslatedInstructions  5938 non-null   object
 2   Cleaned-Ingredients     5938 non-null   object
 3   Ingredient-count        5938 non-null   int64
dtypes: int64(1), object(3)
memory usage: 185.7+ KB

In [ ]:
# train = train.sample(frac = 1)

In [ ]:
train.head()

,TranslatedRecipeName,TranslatedInstructions,Cleaned-Ingredients,Ingredient-count
0,Masala Karela Recipe,"To begin making the Masala Karela Recipe,de-se...","salt,amchur (dry mango powder),karela (bitter ...",10
1,Spicy Tomato Rice (Recipe),"To make tomato puliogere, first cut the tomato...","tomato,salt,chickpea lentils,green chilli,rice...",12
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"To begin making the Ragi Vermicelli Recipe, fi...","salt,rice vermicelli noodles (thin),asafoetida...",12
3,Gongura Chicken Curry Recipe - Andhra Style Go...,To begin making Gongura Chicken Curry Recipe f...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",15
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"To make Andhra Style Alam Pachadi, first heat ...","tomato,salt,ginger,red chillies,curry,asafoeti...",12

In [ ]:
import re
from nltk.stem import WordNetLemmatizer
stop_words= set(stopwords.words('english'))

In [ ]:
# lem= WordNetLemmatizer()
# for i,row in train.iterrows():
#   filter_sentence=[]
#   sentence=row['TranslatedInstructions']
#   sentence=re.sub(r'[^\w\s]','',sentence)
#   words=nltk.word_tokenize(sentence)
#   words=[w for w in words if not w in stop_words]
#   for w in words:
#     filter_sentence.append(lem.lemmatize(w))
#   print(filter_sentence)
#   train.loc[i,'directions']=' '.join(filter_sentence)

In [ ]:
# lem= WordNetLemmatizer()
# for i,row in train.iterrows():
#   filter_sentence=[]
#   sentence=row['Cleaned-Ingredients']
#   sentence=re.sub(r'[^\w\s]','',sentence)
#   words=nltk.word_tokenize(sentence)
#   words=[w for w in words if not w in stop_words]
#   for w in words:
#     filter_sentence.append(lem.lemmatize(w))
#   print(filter_sentence)
#   train.loc[i,'ingredients']=' '.join(filter_sentence)

In [ ]:
# lem= WordNetLemmatizer()
# for i,row in train.iterrows():
#   filter_sentence=[]
#   sentence=row['TranslatedRecipeName']
#   sentence=re.sub(r'[^\w\s]','',sentence)
#   words=nltk.word_tokenize(sentence)
#   words=[w for w in words if not w in stop_words]
#   for w in words:
#     filter_sentence.append(lem.lemmatize(w))
#   print(filter_sentence)
#   train.loc[i,'recipe_name']=' '.join(filter_sentence)

In [ ]:
train.head()

,TranslatedRecipeName,TranslatedInstructions,Cleaned-Ingredients,Ingredient-count
0,Masala Karela Recipe,"To begin making the Masala Karela Recipe,de-se...","salt,amchur (dry mango powder),karela (bitter ...",10
1,Spicy Tomato Rice (Recipe),"To make tomato puliogere, first cut the tomato...","tomato,salt,chickpea lentils,green chilli,rice...",12
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"To begin making the Ragi Vermicelli Recipe, fi...","salt,rice vermicelli noodles (thin),asafoetida...",12
3,Gongura Chicken Curry Recipe - Andhra Style Go...,To begin making Gongura Chicken Curry Recipe f...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",15
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"To make Andhra Style Alam Pachadi, first heat ...","tomato,salt,ginger,red chillies,curry,asafoeti...",12

In [ ]:
#train["ing"]= [train[ing].append('chicken') if i == 'Chicken' else 0 for i in train['TranslatedRecipeName']]
# for i in train['Cleaned-Ingredients']:
#   i == 'chicken'
#   train[ing].append('chicken')

In [ ]:
def extract_keywords(recipe_text):
  # Tokenization
  tokens = nltk.word_tokenize(recipe_text)

  # Remove stop words
  stop_words = set(stopwords.words('english'))
  filtered_tokens = [word for word in tokens if word not in stop_words]


  # Part-of-speech tagging
  tagged = nltk.pos_tag(filtered_tokens)

  # Extract nouns and adjectives
  keywords = [word for word, tag in tagged if tag.startswith('NN') or tag.startswith('JJ')]

  return keywords

all_keywords = []

# Call the function outside of the function definition to avoid recursion
for index, row in train.iterrows():
    text = row['TranslatedInstructions']
    keywords = extract_keywords(text)
    #print(f"Keywords for recipe {index}: {keywords}")
    train.at[index, 'TranslatedInstructions'] = ' '.join(keywords)
    all_keywords.append(keywords) # Append keywords for current row

# Assign the list of keyword lists to the 'Keywords' column
train['Keywords'] = all_keywords

In [ ]:
train.head()

,TranslatedRecipeName,TranslatedInstructions,Cleaned-Ingredients,Ingredient-count,Keywords
0,Masala Karela Recipe,Masala Karela Recipe de-seed karela slice skin...,"salt,amchur (dry mango powder),karela (bitter ...",10,"[Masala, Karela, Recipe, de-seed, karela, slic..."
1,Spicy Tomato Rice (Recipe),tomato first cut tomatoes mixer puree heat oil...,"tomato,salt,chickpea lentils,green chilli,rice...",12,"[tomato, first, cut, tomatoes, mixer, puree, h..."
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,Ragi Vermicelli Recipe first steam ragi vermic...,"salt,rice vermicelli noodles (thin),asafoetida...",12,"[Ragi, Vermicelli, Recipe, first, steam, ragi,..."
3,Gongura Chicken Curry Recipe - Andhra Style Go...,Gongura Chicken Curry Recipe ingredients small...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",15,"[Gongura, Chicken, Curry, Recipe, ingredients,..."
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,Andhra Style Alam Pachadi heat oil pan Add coo...,"tomato,salt,ginger,red chillies,curry,asafoeti...",12,"[Andhra, Style, Alam, Pachadi, heat, oil, pan,..."

In [ ]:
# # ohe= OneHotEncoder()
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()

In [ ]:
# # ohe.fit_transform(train[['recipe_name', 'ingredients', 'directions']]).toarray()
# train['TranslatedInstructions'] = label_encoder.fit_transform(train['TranslatedInstructions'])

In [ ]:
# # feature =ohe.fit_transform(train[['recipe_name', 'ingredients', 'directions']]).toarray()
# train['Cleaned-Ingredients'] = label_encoder.fit_transform(train['Cleaned-Ingredients'])

In [ ]:
# ohe.categories_
train.head()

,TranslatedRecipeName,TranslatedInstructions,Cleaned-Ingredients,Ingredient-count,Keywords
0,Masala Karela Recipe,Masala Karela Recipe de-seed karela slice skin...,"salt,amchur (dry mango powder),karela (bitter ...",10,"[Masala, Karela, Recipe, de-seed, karela, slic..."
1,Spicy Tomato Rice (Recipe),tomato first cut tomatoes mixer puree heat oil...,"tomato,salt,chickpea lentils,green chilli,rice...",12,"[tomato, first, cut, tomatoes, mixer, puree, h..."
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,Ragi Vermicelli Recipe first steam ragi vermic...,"salt,rice vermicelli noodles (thin),asafoetida...",12,"[Ragi, Vermicelli, Recipe, first, steam, ragi,..."
3,Gongura Chicken Curry Recipe - Andhra Style Go...,Gongura Chicken Curry Recipe ingredients small...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",15,"[Gongura, Chicken, Curry, Recipe, ingredients,..."
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,Andhra Style Alam Pachadi heat oil pan Add coo...,"tomato,salt,ginger,red chillies,curry,asafoeti...",12,"[Andhra, Style, Alam, Pachadi, heat, oil, pan,..."

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5938 entries, 0 to 5937
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   TranslatedRecipeName    5938 non-null   object
 1   TranslatedInstructions  5938 non-null   object
 2   Cleaned-Ingredients     5938 non-null   object
 3   Ingredient-count        5938 non-null   int64
 4   Keywords                5938 non-null   object
dtypes: int64(1), object(4)
memory usage: 232.1+ KB

In [ ]:
# feature_labels = ohe.categories_

In [ ]:
# feature_labels = np.array(feature_labels).ravel()

In [ ]:
# pd.DataFrame(feature, columns=feature_labels)

In [ ]:
# prompt: Using dataframe train: train this dataframe using a neural network to build a chatbot.

# This task is too complex to be completed here. Building a chatbot using a neural network requires:

# 1. **Data Preprocessing**: Cleaning and preparing the text data (tokenization, stemming/lemmatization, etc.)
# 2. **Model Selection**: Choosing an appropriate neural network architecture (e.g., Seq2Seq, Transformer)
# 3. **Training**: Training the model on the preprocessed data
# 4. **Evaluation**: Assessing the model's performance on a held-out dataset
# 5. **Deployment**: Integrating the trained model into a chatbot application.

# This process involves extensive code and cannot be condensed into a single response.

In [ ]:
# def preprocess_text(text):
#     tokens = word_tokenize(text)
#     tokens = [word for word in tokens if word.isalpha()]
#     stop_words = set(stopwords.words('english'))
#     tokens = [word for word in tokens if not word in stop_words]
#     return ' '.join(tokens)

In [ ]:
# train = df.drop(['yield', 'rating', 'url', 'cuisine_path', 'img_src'], axis=1)
# train['in'] = train['ingredients'].apply(preprocess_text)

# print(df.head())

In [ ]:
# train['ti'] = train['timing'].apply(preprocess_text)
# train['nut'] = train['nutrition'].apply(preprocess_text)
# train['dir'] = train['directions'].apply(preprocess_text)
# train['rip'] = train['recipe_name'].apply(preprocess_text)

In [ ]:
# train.fillna(0)

In [ ]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# label_encoder_x= LabelEncoder()
# train[:]= label_encoder_x.fit_transform(train[10])
# #Encoding for dummy variables
# onehot_encoder= OneHotEncoder(categorical_features= [0])
# x= onehot_encoder.fit_transform(x).toarray()

In [ ]:
# def create_vocabulary_from_dataframe(df, text_columns):
#   """Creates a vocabulary from multiple text columns in a pandas DataFrame.

#   Args:
#     df: A pandas DataFrame.
#     text_columns: A list of column names containing text data.

#   Returns:
#     A dictionary mapping words to indices.
#   """

#   words = []
#   for col in text_columns:
#     words.extend([word for sentence in df[col] for word in sentence.split()])
#   unique_words = set(words)
#   vocab = {word: i+1 for i, word in enumerate(unique_words)}  # Start indices from 1
#   vocab['<UNK>'] = 0
#   return vocab

# def encode_text_from_dataframe(df, text_columns, vocab):
#   """Encodes text data from multiple text columns in a pandas DataFrame into numerical sequences.

#   Args:
#     df: A pandas DataFrame.
#     text_columns: A list of column names containing text data.
#     vocab: A dictionary mapping words to indices.

#   Returns:
#     A list of lists of encoded sequences, where each inner list corresponds to a column.
#   """

#   encoded_data = []
#   for col in text_columns:
#     column_encoded = []
#     for sentence in df[col]:
#       encoded_sentence = [vocab.get(word, 0) for word in sentence.split()]  # Use 0 for <UNK>
#       column_encoded.append(encoded_sentence)
#     encoded_data.append(column_encoded)
#   return encoded_data
# # Example usage
# data = {'text1': ['rip'], 'text2': ['dir'], 'text3': ['nut'], 'text4': ['ti'], 'text5': ['in']}
# df = pd.DataFrame(data)

# text_columns = ['text5']
# t_c= ['text1']

# vocab = create_vocabulary_from_dataframe(df, text_columns)
# encoded_data = encode_text_from_dataframe(df, text_columns, vocab)

In [ ]:
# train.head()

In [ ]:
# model = Sequential([
#     Embedding(input_dim=10, output_dim=64, input_length=10000),
#     LSTM(128),
#     Dense(25, activation='softmax')
# ])

In [ ]:
from sklearn.model_selection import train_test_split

# Select features (X) and target variable (y)
x = train['Keywords']  # Use a list to select multiple columns
y = train['TranslatedInstructions']  # Assuming you want the same columns for the target

# Split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [ ]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_train)
x_train_sequences = tokenizer.texts_to_sequences(x_train)

In [ ]:
max_sequence_length = 1000
x_train_padded = tf.keras.preprocessing.sequence.pad_sequences(x_train_sequences, maxlen=max_sequence_length)

x_train_flattened = x_train_padded.reshape(x_train_padded.shape[0], -1)

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
num_classes = len(label_encoder.classes_)

y_train_one_hot = to_categorical(y_train_encoded, num_classes=num_classes)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(3, activation='relu', input_shape=(x_train_flattened.shape[1],)), # Specify input shape to the first layer
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(num_classes, activation='softmax')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
print("Shape of x_train_flattened:", x_train_flattened)
print("Shape of y_train_one_hot:", y_train_one_hot.shape)

Shape of x_train_flattened: [[   0    0    0 ...  768  105  461]
 [   0    0    0 ...   72  105  461]
 [   0    0    0 ... 3470 1106  696]
 ...
 [   0    0    0 ...    1  297   65]
 [   0    0    0 ...    1  271  131]
 [   0    0    0 ...   21  220  131]]
Shape of y_train_one_hot: (4156, 4155)

In [ ]:
train.head()

,TranslatedRecipeName,TranslatedInstructions,Cleaned-Ingredients,Ingredient-count,Keywords
0,Masala Karela Recipe,Masala Karela Recipe de-seed karela slice skin...,"salt,amchur (dry mango powder),karela (bitter ...",10,"[Masala, Karela, Recipe, de-seed, karela, slic..."
1,Spicy Tomato Rice (Recipe),tomato first cut tomatoes mixer puree heat oil...,"tomato,salt,chickpea lentils,green chilli,rice...",12,"[tomato, first, cut, tomatoes, mixer, puree, h..."
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,Ragi Vermicelli Recipe first steam ragi vermic...,"salt,rice vermicelli noodles (thin),asafoetida...",12,"[Ragi, Vermicelli, Recipe, first, steam, ragi,..."
3,Gongura Chicken Curry Recipe - Andhra Style Go...,Gongura Chicken Curry Recipe ingredients small...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",15,"[Gongura, Chicken, Curry, Recipe, ingredients,..."
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,Andhra Style Alam Pachadi heat oil pan Add coo...,"tomato,salt,ginger,red chillies,curry,asafoeti...",12,"[Andhra, Style, Alam, Pachadi, heat, oil, pan,..."

In [ ]:
# x_sample = tfdf.keras.pd_dataframe_to_tf_dataset(train, label="TranslatedInstructions", max_num_classes=6000) # Set an explicit upper limit for the number of classes
# x_sam = tfdf.keras.pd_dataframe_to_tf_dataset(train, label="Cleaned-Ingredients", max_num_classes=6000) # Set an explicit upper limit for the number of classes

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train_flattened, y_train_one_hot, epochs=8000, batch_size=36)

Streaming output truncated to the last 5000 lines.
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0853 - loss: 5.6943
Epoch 651/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0845 - loss: 5.6841
Epoch 652/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0914 - loss: 5.6504
Epoch 653/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0811 - loss: 5.7596
Epoch 654/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0151 - loss: 6.9633
Epoch 655/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0200 - loss: 6.4478
Epoch 656/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0467 - loss: 5.9792
Epoch 657/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0519 - loss: 5.9257
Epoch 658/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0759 - loss: 5.7248
Epoch 659/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0716 - loss: 5.7449
Epoch 660/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0771 - loss: 5.7458
Epoch 661/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0736 - loss: 5.7408
Epoch 662/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0940 - loss: 5.7340
Epoch 663/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0664 - loss: 6.0482
Epoch 664/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0587 - loss: 6.0294
Epoch 665/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0543 - loss: 6.0662
Epoch 666/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0595 - loss: 5.9218
Epoch 667/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0621 - loss: 5.7840
Epoch 668/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0880 - loss: 5.6540
Epoch 669/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0825 - loss: 5.7195
Epoch 670/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0796 - loss: 5.6566
Epoch 671/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0851 - loss: 5.6571
Epoch 672/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0932 - loss: 5.5978
Epoch 673/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0880 - loss: 5.6377
Epoch 674/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0914 - loss: 5.6083
Epoch 675/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0965 - loss: 5.6060
Epoch 676/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0856 - loss: 5.7139
Epoch 677/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0830 - loss: 5.6593
Epoch 678/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0686 - loss: 5.7452
Epoch 679/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0890 - loss: 5.6093
Epoch 680/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1047 - loss: 5.5845
Epoch 681/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1103 - loss: 5.5793
Epoch 682/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0930 - loss: 5.6604
Epoch 683/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0975 - loss: 5.7138
Epoch 684/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0992 - loss: 5.6941
Epoch 685/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1043 - loss: 5.5986
Epoch 686/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0865 - loss: 5.6735
Epoch 687/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0957 - loss: 5.5607
Epoch 688/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1056 - loss: 5.5526
Epoch 689/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1003 - loss: 5.5838
Epoch 690/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0915 - loss: 5.6524
Epoch 691/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1082 - loss: 5.6025
Epoch 692/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1010 - loss: 5.5615
Epoch 693/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1123 - loss: 5.6038
Epoch 694/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1109 - loss: 5.5085
Epoch 695/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0651 - loss: 5.8906
Epoch 696/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0827 - loss: 5.7169
Epoch 697/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0866 - loss: 5.6492
Epoch 698/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0897 - loss: 5.6785
Epoch 699/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0763 - loss: 5.8103
Epoch 700/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0654 - loss: 5.8161
Epoch 701/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0765 - loss: 5.6890
Epoch 702/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0903 - loss: 5.6169
Epoch 703/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0700 - loss: 5.8739
Epoch 704/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0493 - loss: 5.9633
Epoch 705/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0579 - loss: 5.9050
Epoch 706/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0572 - loss: 6.0074
Epoch 707/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0676 - loss: 6.0095
Epoch 708/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0733 - loss: 5.9565
Epoch 709/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0635 - loss: 5.9655
Epoch 710/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0837 - loss: 5.8348
Epoch 711/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0834 - loss: 5.7793
Epoch 712/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0773 - loss: 5.7736
Epoch 713/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0911 - loss: 5.6966
Epoch 714/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0601 - loss: 6.0409
Epoch 715/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0675 - loss: 5.9126
Epoch 716/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0804 - loss: 5.7195
Epoch 717/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0804 - loss: 5.7100
Epoch 718/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0874 - loss: 5.7296
Epoch 719/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0866 - loss: 5.6837
Epoch 720/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0801 - loss: 5.6698
Epoch 721/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0778 - loss: 5.8074
Epoch 722/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0734 - loss: 6.0789
Epoch 723/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0908 - loss: 5.9657
Epoch 724/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1020 - loss: 5.6123
Epoch 725/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0952 - loss: 5.6439
Epoch 726/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0821 - loss: 5.7159
Epoch 727/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0980 - loss: 5.6667
Epoch 728/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0937 - loss: 5.6327
Epoch 729/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0998 - loss: 5.5841
Epoch 730/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0919 - loss: 5.6180
Epoch 731/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1094 - loss: 5.5512
Epoch 732/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1042 - loss: 5.6108
Epoch 733/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0985 - loss: 5.6252
Epoch 734/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1039 - loss: 5.5988
Epoch 735/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1045 - loss: 5.5890
Epoch 736/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1055 - loss: 5.5764
Epoch 737/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0749 - loss: 5.8298
Epoch 738/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0798 - loss: 5.8382
Epoch 739/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0806 - loss: 5.8176
Epoch 740/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0679 - loss: 5.9312
Epoch 741/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0737 - loss: 5.7710
Epoch 742/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0787 - loss: 5.8035
Epoch 743/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0667 - loss: 5.8312
Epoch 744/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0530 - loss: 6.2227
Epoch 745/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0539 - loss: 6.1178
Epoch 746/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0641 - loss: 5.9437
Epoch 747/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0781 - loss: 5.8553
Epoch 748/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0741 - loss: 5.8575
Epoch 749/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0802 - loss: 5.8588
Epoch 750/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0384 - loss: 6.2324
Epoch 751/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0551 - loss: 6.0602
Epoch 752/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0626 - loss: 5.8176
Epoch 753/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0550 - loss: 5.9780
Epoch 754/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0445 - loss: 6.0913
Epoch 755/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0439 - loss: 6.2848
Epoch 756/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0363 - loss: 6.2572
Epoch 757/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0603 - loss: 5.8325
Epoch 758/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0491 - loss: 6.0178
Epoch 759/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0780 - loss: 5.7914
Epoch 760/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0603 - loss: 6.1530
Epoch 761/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0687 - loss: 5.9267
Epoch 762/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0734 - loss: 5.8520
Epoch 763/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0614 - loss: 5.9702
Epoch 764/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0640 - loss: 5.8841
Epoch 765/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0636 - loss: 5.8885
Epoch 766/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0724 - loss: 5.9180
Epoch 767/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0733 - loss: 5.8375
Epoch 768/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0587 - loss: 5.8529
Epoch 769/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0802 - loss: 5.7959
Epoch 770/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0757 - loss: 5.7658
Epoch 771/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0761 - loss: 5.8925
Epoch 772/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0663 - loss: 5.7817
Epoch 773/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0792 - loss: 5.6890
Epoch 774/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0907 - loss: 5.6570
Epoch 775/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0944 - loss: 5.6941
Epoch 776/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0782 - loss: 5.7061
Epoch 777/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0930 - loss: 5.6284
Epoch 778/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0785 - loss: 5.7344
Epoch 779/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0662 - loss: 5.7740
Epoch 780/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0824 - loss: 5.7125
Epoch 781/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0717 - loss: 5.6944
Epoch 782/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0725 - loss: 5.7335
Epoch 783/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0801 - loss: 5.8240
Epoch 784/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0786 - loss: 5.8317
Epoch 785/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0658 - loss: 5.7959
Epoch 786/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0799 - loss: 5.7604
Epoch 787/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0880 - loss: 5.6963
Epoch 788/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0954 - loss: 5.6623
Epoch 789/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0766 - loss: 5.7903
Epoch 790/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0673 - loss: 5.7460
Epoch 791/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0834 - loss: 5.6988
Epoch 792/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0443 - loss: 6.0854
Epoch 793/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0727 - loss: 5.7520
Epoch 794/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0891 - loss: 5.8024
Epoch 795/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0775 - loss: 5.7065
Epoch 796/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0851 - loss: 5.7917
Epoch 797/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0893 - loss: 5.6333
Epoch 798/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0697 - loss: 5.9755
Epoch 799/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0760 - loss: 5.8288
Epoch 800/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0696 - loss: 5.7940
Epoch 801/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0837 - loss: 5.7693
Epoch 802/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0752 - loss: 5.8730
Epoch 803/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0600 - loss: 6.0168
Epoch 804/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0306 - loss: 6.6461
Epoch 805/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0523 - loss: 6.4213
Epoch 806/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0576 - loss: 6.2440
Epoch 807/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0620 - loss: 6.2383
Epoch 808/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0702 - loss: 6.1266
Epoch 809/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0657 - loss: 6.0847
Epoch 810/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0795 - loss: 5.9678
Epoch 811/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0704 - loss: 5.7649
Epoch 812/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0729 - loss: 5.7932
Epoch 813/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0774 - loss: 5.7766
Epoch 814/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0723 - loss: 5.7541
Epoch 815/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0834 - loss: 5.6517
Epoch 816/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0840 - loss: 5.6721
Epoch 817/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0906 - loss: 5.6272
Epoch 818/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0885 - loss: 5.7162
Epoch 819/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0923 - loss: 5.6614
Epoch 820/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0732 - loss: 5.7381
Epoch 821/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0903 - loss: 5.6438
Epoch 822/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0890 - loss: 5.7436
Epoch 823/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0857 - loss: 5.6606
Epoch 824/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0877 - loss: 5.8916
Epoch 825/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0629 - loss: 5.9678
Epoch 826/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0840 - loss: 5.6915
Epoch 827/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0808 - loss: 5.6670
Epoch 828/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0824 - loss: 5.7817
Epoch 829/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0396 - loss: 6.1402
Epoch 830/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0767 - loss: 5.7301
Epoch 831/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0694 - loss: 5.7318
Epoch 832/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0959 - loss: 5.5825
Epoch 833/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0856 - loss: 5.6446
Epoch 834/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0926 - loss: 5.6345
Epoch 835/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0986 - loss: 5.6285
Epoch 836/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0833 - loss: 5.6776
Epoch 837/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0961 - loss: 5.5711
Epoch 838/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1037 - loss: 5.5838
Epoch 839/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1039 - loss: 5.6092
Epoch 840/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1020 - loss: 5.6288
Epoch 841/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1146 - loss: 5.5094
Epoch 842/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1144 - loss: 5.5083
Epoch 843/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1085 - loss: 5.5307
Epoch 844/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0731 - loss: 5.8822
Epoch 845/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0897 - loss: 5.8063
Epoch 846/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0782 - loss: 6.0114
Epoch 847/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0605 - loss: 5.9487
Epoch 848/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0617 - loss: 5.8230
Epoch 849/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0795 - loss: 5.7736
Epoch 850/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0793 - loss: 5.6947
Epoch 851/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0832 - loss: 5.7574
Epoch 852/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0889 - loss: 5.6528
Epoch 853/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0781 - loss: 5.7221
Epoch 854/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0718 - loss: 5.8642
Epoch 855/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0826 - loss: 5.7593
Epoch 856/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0853 - loss: 5.6761
Epoch 857/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0866 - loss: 5.7892
Epoch 858/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0949 - loss: 5.6362
Epoch 859/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1032 - loss: 5.5804
Epoch 860/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0865 - loss: 5.6811
Epoch 861/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0794 - loss: 5.8346
Epoch 862/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0935 - loss: 5.5566
Epoch 863/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0541 - loss: 6.5774
Epoch 864/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0754 - loss: 5.9257
Epoch 865/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0519 - loss: 6.1320
Epoch 866/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0545 - loss: 5.8648
Epoch 867/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0663 - loss: 5.8947
Epoch 868/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0691 - loss: 5.7561
Epoch 869/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0605 - loss: 5.9169
Epoch 870/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0743 - loss: 5.8139
Epoch 871/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0586 - loss: 5.8940
Epoch 872/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0565 - loss: 5.8111
Epoch 873/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0780 - loss: 5.7233
Epoch 874/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0908 - loss: 5.6690
Epoch 875/5000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0904 - loss: 5.6451
Epoch 876/5000

KeyboardInterrupt:

In [ ]:
# import tensorflow as tf
# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.utils import to_categorical

# # ... (your existing code for label encoding) ...

# # Tokenize the text data
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(x_train)
# x_train_sequences = tokenizer.texts_to_sequences(x_train)
# x_test_sequences = tokenizer.texts_to_sequences(x_test)

# max_sequence_length = 1000  # Adjust based on your data analysis
# x_train_padded = tf.keras.preprocessing.sequence.pad_sequences(x_train_sequences, maxlen=max_sequence_length)
# x_test_padded = tf.keras.preprocessing.sequence.pad_sequences(x_test_sequences, maxlen=max_sequence_length)

# # Flatten sequences for Dense layers
# x_train_flattened = x_train_padded.reshape(x_train_padded.shape[0], -1)
# x_test_flattened = x_test_padded.reshape(x_test_padded.shape[0], -1)

# vocab_size = len(tokenizer.word_index) + 1
# label_encoder = LabelEncoder()
# y_train_encoded = label_encoder.fit_transform(y_train)
# num_classes = len(label_encoder.classes_)



# model_better = keras.Sequential([
#     keras.layers.Dense(16, input_shape=(x_train_flattened.shape[1],), activation='relu'), # Change input_shape to match x_train_flattened
#     keras.layers.Dense(32, activation='relu'),
#     keras.layers.Dense(32, activation='relu'),
#     keras.layers.Dense(num_classes, activation='softmax')  # Use num_classes for output layer
# ])

# # Compiling the model
# model_better.compile(optimizer='adam',
#                      loss=keras.losses.SparseCategoricalCrossentropy(),
#                      metrics=['accuracy'])

# # fitting the model
# model_better.fit(x_train_flattened, y_train_encoded, epochs=10, batch_size=8)

In [ ]:
# inp = "Chicken, Masala"
# # Tokenize the text data
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(inp)
# x_train_sequences = tokenizer.texts_to_sequences(inp)

# # Pad sequences to a uniform length
# max_sequence_length = 1000  # Or determine this based on your data
# x_train_padded = tf.keras.preprocessing.sequence.pad_sequences(x_train_sequences, maxlen=max_sequence_length)

In [ ]:
# predictions = model.predict(x_train_padded)
# predicted_indices = np.argmax(predictions, axis=1)  # Get the index of the predicted class

# # Assuming you have the label encoder from your training process:
# predicted_labels = label_encoder.inverse_transform(predicted_indices)

# print(predicted_labels)

In [ ]:
def pred(ing):
  tokenizer = Tokenizer()
  tokenizer.fit_on_texts(ing)
  x_train_sequences = tokenizer.texts_to_sequences(ing)
  max_sequence_length = 1000  # Or determine this based on your data
  x_train_padded = tf.keras.preprocessing.sequence.pad_sequences(x_train_sequences, maxlen=max_sequence_length)
  predictions = model.predict(x_train_padded)
  predicted_indices = np.argmax(predictions, axis=1)  # Get the index of the predicted class
  predicted_labels = label_encoder.inverse_transform(predicted_indices)
  return predicted_labels

In [ ]:
pred(['Masala Karela Recipe'])

In [ ]:
model.evaluate(x_train_flattened, y_train_one_hot)

In [ ]:
y_pred = model.predict(x_train_flattened)

In [ ]:
y_test

In [ ]:
# X_train = encode_text_from_dataframe(train, text_columns, vocab)
# # y_train = encode_text_from_dataframe(train, t_c, vocab)

In [ ]:
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# model.fit(x_train, y_train_encoded, epochs=10, batch_size=64)

In [ ]:
# print(train['in'].dtype)
# print(train['rip'].dtype)